export default function FileShareEmail(fileName, link) {

  return `
  
  <div style="font-family: Arial, sans-serif; background:#f5f7fb; padding:40px">

    <div style="
      max-width:500px;
      margin:auto;
      background:white;
      border-radius:10px;
      padding:30px;
      box-shadow:0 4px 12px rgba(0,0,0,0.1);
      text-align:center;
    ">

      <h2 style="color:#2563eb;">📁 FileFlux</h2>

      <h3 style="margin-top:10px;">A file was shared with you</h3>

      <p style="color:#555;">
        Someone shared a file with you using <b>FileFlux</b>.
      </p>

      <div style="
        background:#f3f4f6;
        padding:12px;
        border-radius:6px;
        margin:20px 0;
      ">
        <b>${fileName}</b>
      </div>

      <a 
        href="${link}" 
        style="
          display:inline-block;
          background:#2563eb;
          color:white;
          padding:12px 25px;
          border-radius:6px;
          text-decoration:none;
          font-weight:bold;
          margin-top:10px;
        "
      >
        Download File
      </a>

      <p style="margin-top:20px; font-size:12px; color:#888">
        This link was generated by FileFlux.
      </p>

    </div>

  </div>

  `;
}